### ISSUE TITLE
Polish storing Items response of the JS client data

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-starter-corporate-next-js#12]
### Motivation

To get object representation of the Kontent Delivery Client data, the starter is using `JSON.parse(JSON.stringify(` which is not something you would like to use. 

Mostly fixed in #41

> I will keep this issue open right now because there are some plans to refactor the Javascript SDK to make it more modular, which would potentially affect the loading and transforming data approach.

### Proposed solution

* [x] Use some library to cut this out. 
* [x] Select only necessary properties needed (i.e. _raw part of the object is not necessary)
* [ ] Accommodate new modular SDK to prevent fetching `parse5` + `rxjs` library to the client.

### Additional context

CUrrent data loading approach:
* https://github.com/Kentico/kontent-starter-corporate-next-js#data-loading

**Comment by JJCLane** [comment]
This would be a great feature, ideally there would be a way to take the strongly typed models and serialize them. Currently I'm creating my own View Models which take only the values I need like so:

```ts
import { ElementModels } from '@kentico/kontent-delivery';

export default class Image {
  public url: string;

  public description: string;

  public width: number;

  public height: number;

  constructor(asset: ElementModels.AssetModel) {
    if (!asset) return;
    this.url = asset.url;
    this.description = asset.description;
    this.width = asset.width;
    this.height = asset.height;
  }

  static getIntrinsicSize(width: number, height: number, maxWidth: number): { width: number; height: number } {
    const bestRatio = Math.min(1, maxWidth / width);
    return { width: width * bestRatio, height: height * bestRatio };
  }

  toJSON() {
    if (this.url === undefined) {
      return null;
    }
    return {
      url: this.url,
      description: this.description,
      width: this.width,
      height: this.height,
    };
  }
}

```

**Comment by Simply007** [comment]
Addin related pull request, that solved the `JSON.stringify` serialization #41.

The approach is described in [Data loading section in README](https://github.com/Kentico/kontent-starter-corporate-next-js#data-loading).

@JJCLane - it might be possible to adjust the `hydrateContentItemSingleResponse/hydrateContentItemListingResponse` and provide a `queryConfig` as a second parameter and provide a `TypeProvider` for Javascript SDK. I haven't tested it out yet though.

I will keep this issue opened right now because there are some plans to refactor the Javascript SDK to make it more modular, which would potentially affect the loading and transforming data approach.

**Comment by JJCLane** [comment]
Ah ok, does that mean that you'd incur double hydration costs for a page load?

**Comment by Simply007** [comment]
The hydration itself does not cost that much - transferring JSON objects into the ContentItems (or strongly types if you gave the type provider) is pretty quick. 

>  Static Next.js properties do not allow classes to be passed through - it has to be [serializable objects](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation)

But you are right before it was:

Request -> JSON.Stringify  ->  Static Next.js props -> React props -> components 

Now it is:

Request -> first hydration, that is discarded + parse out just raw JSONs -> Static Next.js props -> Second hydration (no second request - using static Next.js props) -> React props -> components

Ideal solution:

Request -> response based on interfaces instead of classes -> Static Next.js props -> React props -> components

The current problem is mainly the classes-based models + the `parse5` + `rxjs` library which is now required on the client and these two libraries are pretty big and not necessary in this case since the Rich text is [resolved the different way](https://github.com/Kentico/kontent-starter-corporate-next-js#rich-text-element-resolution).

**Comment by Simply007** [comment]
> Yep, it seems like currently it's a trade off, if you want to be more efficient, there is some manual effort involved setting up serializable models, be happy to use `JSON.parse(JSON.serialize())` or the flow described above. I'd love to get to a point where it was a more seamless developer experience :) I've been using Next.js + Kontent for a while now, so if you need any input, I'd open to that.

Perfect @JJCLane - my intentions are the same. To have solid Next.js + Kontent practices for projects with the best developer experience possible.

If you have some time, It would be great to connect with me on Discord ([My personal profile](https://discord.com/users/507100760144871434), or you can find me on [Kontent Discord as well](https://bit.ly/kontent-discord)).

If you prefer to book a specific time slot, please [use this booking page](https://outlook.office365.com/owa/calendar/OndejChrastina@kenticosoftware.onmicrosoft.com/bookings/).

**Comment by Simply007** [comment]
Currently not an issue anymore since the serialization and deserialization is already done using [new data loading approach](https://github.com/Kentico/kontent-starter-corporate-next-js#data-loading).
