### ISSUE TITLE
Improve link rendering from RTE

### ISSUE THREAD

**Issue by JJCLane** [Kentico/kontent-starter-corporate-next-js#42]
Currently the link will only render the first child, I believe this could be handled better through the use of `domToReact`.

https://github.com/Kentico/kontent-starter-corporate-next-js/blob/13291209cfd177849e272b37ee72d4707301005d/components/RichText.js#L91-L93

```tsx
<Link href={url}> 
    {domToReact(domNode.children)}
 </Link>
```

**Comment by Simply007** [comment]
Implemented - thanks @JJCLane  for the improvement tip.

And [as I said earlier](https://github.com/Kentico/kontent-starter-corporate-next-js/issues/12#issuecomment-838203478) - I would be super glad if you find some time to discuss your feedback on the starter.
