### ISSUE TITLE
Cannot import kontent-backup.zip to 

### ISSUE THREAD

**Issue by jordan-ghost** [Kentico/kontent-starter-corporate-next-js#48]
### Brief bug description

While following the instructions in the readme, I encountered a failure of the provided tools to allow importing of the zipped data provided in this repo. Using both the online 'Kontent Template Manager' and the CLI tool 'Kontent Backup Manager' which underlies it, I get the following error:

> There was an error processing your request:  Error: Invalid file 'workflowSteps.json'

If I unzip the file, there is no `workflowSteps.json` inside the zip.

Thinking the zip might be corrupted, I re-zipped the file contents, but it just made the error report on `assets.json` instead. `assets.json` exists, which is something, and is a valid, well-formed JSON file according to an online syntax validator.

### Repro steps (browser)

1. Download this repository
2. Go to https://kentico.github.io/kontent-template-manager/import
3. Add `kontent-backup.zip` from this repo to the file upload on this page
4. Fill in project ID and API Key 
5. Checkmark button turns green
6. Click 'Prepare for import'

**Expect**: See a UI for confirming the import of the uploaded files into the specified project (I assume).
**Actual**: UI remains blank while processing the zipfile. Javascript console shows the above error message.

### Repro steps (CLI)

1. Download this repository
2. Install `@kentico/kontent-backup-manager` globally using npm or yarn
3. Run `kbm --action=restore --projectId=<$PID> --apiKey=<$MGMT_API_KEY> --zipFilename=kontent-backup`

**Expect**: System will upload and import the backup zip
**Actual**: Terminal gives the following output:
```
Reading file './kontent-backup.zip'
Reading file completed
Unzipping file
Parsing zip contents
There was an error processing your request:  Error: Invalid file 'workflowSteps.json'
```

### Test environment

 - Platform/OS: MacOS 10.14
 - Browser: Chrome v92
 - Node: v13.14
 - NPM: v6.14.4

**Comment by Simply007** [comment]
Hello @jordan-ghost,

thanks for reporting the issue. We have recently released new version Kontent backup manager as well as template manager.

Quick workaround would be to use version defined in `kontent-backup.zip/metadata.json` which is `1.14.0`. So use:

´´´sh
npm i -g @kentico/kontent-backup-manager@1.14.0
// or
yarn global add  @kentico/kontent-backup-manager@1.14.0
´´´

Or wait a bit, I will update backup.zip in a couple of minutes.

**Comment by Simply007** [comment]
@jordan-ghost - You should now be able to import `kontent-backup.js`.

After the import, you will need to manually publish all items. There is probably a bug in the backup manager https://github.com/Kentico/kontent-backup-manager-js/issues/19 that does not publish the content items automatically.

**Comment by Simply007** [comment]
@jordan-ghost 

Everything should work (also the publish items problem was fixed).

If you find any problems feel free to re-open the issue.

**Comment by jordan-ghost** [comment]
@Simply007 Thanks for your prompt assistance :) The updated kontent-backup.zip imported fine and I'm back on track 👍 

Cheers!
