### ISSUE TITLE
run build required?

### ISSUE THREAD

**Issue by CAtSG** [Kentico/kontent-starter-corporate-next-js#55]
Hi,

After creating a new page for the main menu in Kontent, the page shows up in the main menu but it will result in a 404 unless I rebuild.  Is this expected?

Thanks!

**Comment by Simply007** [comment]
Hello @CAtSG,

it really depends on the fetching data approach. If you use [ISR](https://github.com/Kentico/kontent-starter-corporate-next-js#incremental-static-regeneration-isr), it should be done automatically. I have tested this approach on starter.

https://webmshare.com/5KoEK

[Static export](https://github.com/Kentico/kontent-starter-corporate-next-js#static) requires you to rebuild the site for any update you want to propagate.

There is also the possibility to use [Server-side rendering](https://github.com/Kentico/kontent-starter-corporate-next-js#server-side-rendering), but this approach is not covered in this starter.

**Comment by CAtSG** [comment]
Hi,

I am using ISR as well.  For me it works as you have demonstrated when I ‘npm run dev’ but it doesn’t work when I ‘npm run build’ then ‘npm run start’.

Thanks,
Calvin

**Comment by CAtSG** [comment]
Hi,

I have inadvertently included personal info in my reply.  Please could you help delete it?

Thanks

**Comment by Simply007** [comment]
> Hi, I have inadvertently included personal info in my reply. Please could you help delete it? Thanks

It is deleted.

**Comment by Simply007** [comment]
> I ‘npm run build’ then ‘npm run start’.

I am not sure what might cause it.

You might want to check the build log of the application I have used for preparation: https://app.netlify.com/sites/kontent-starter-corporate-next-js/deploys/614dd5f6212c0900073a17ec

**Comment by Simply007** [comment]
I have double-checked the `yarn build` and `yarn start` locally because I have spotted the issue in Netlify log (https://github.com/netlify/netlify-plugin-nextjs/blob/main/docs/caveats.md#incremental-static-regeneration) but locally it works exactly the same for the starter.
